### ISSUE TITLE
Cannot mock BufferedReader

### ISSUE THREAD

**Issue by Atry** [paulbutcher/ScalaMock#265]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)
4.2.0

### Scala Version (e.g. 2.12)
2.12.8

### Runtime (JVM or JS)
JVM

### Please describe the expected behavior of the issue
```
git clone https://github.com/Atry/mockreader.git && cd mockreader && sbt test
```

```
Cloning into 'mockreader'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 10 (delta 0), reused 10 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins/project
[info] Loading settings for project global-plugins from idea.sbt,mavenResolvers.sbt,metals.sbt ...
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins
[info] Loading project definition from /private/tmp/mockreader/project
[info] Updating ProjectRef(uri("file:/private/tmp/mockreader/project/"), "mockreader-build")...
[info] Done updating.
[info] Loading settings for project mockreader from build.sbt ...
[info] Set current project to mockreader (in build file:/private/tmp/mockreader/)
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/mockreader/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] MyTest:
[info] - mock bufferedreader *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at java.io.Reader.<init>(Reader.java:78)
[info]   at java.io.BufferedReader.<init>(BufferedReader.java:101)
[info]   at mypackage.MyTest$$anon$1.<init>(MyTest.scala:4)
[info]   at mypackage.MyTest.$anonfun$new$1(MyTest.scala:4)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:405)
[info]   ...
[info] Run completed in 406 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	mypackage.MyTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed 2019-6-13 2:58:01
```

### Please provide a description of what actually happens
A `NullPointerException` is thrown.

### Reproducible Test Case

```scala
package mypackage
class MyTest extends org.scalatest.FreeSpec with org.scalamock.scalatest.MockFactory {
  "mock bufferedreader" in {
    mock[java.io.BufferedReader]
  }
}
```

**Comment by barkhorn** [comment]
You will need to subclass `BufferedReader` yourself and supply something valid in the constructor for `Reader`.
ScalaMock uses anonymous subclasses for mocks, and can only supply a `null` for parameters, hence the NullpointerException. This is not a bug but expected behaviour, as the constructors of all superclasses (type to mock, and its parents) still run. You can see this from the stack trace.
The only way around this is to subclass it, e.g.

```scala
import java.io.{BufferedReader, Reader}

import org.scalamock.scalatest.MockFactory
import org.scalatest.FunSuite

class Issue265Test extends FunSuite with MockFactory {
  test("mock bufferedreader") {
    val r = mock[Reader]
    class MockableBR extends BufferedReader(r)
    val br = mock[MockableBR]
    // ...
  }
}
```

**Comment by Atry** [comment]
IIRC, Mockito allows `mock(BufferedReader.class)`.
