### ISSUE TITLE
Verify on stubs in property-checks with scalacheck fails

### ISSUE THREAD

**Issue by janjaali** [paulbutcher/ScalaMock#272]
### ScalaMock Version (e.g. 3.5.0)
4.4.0

### Scala Version (e.g. 2.12)
2.13.0

### Runtime (JVM or JS)
JVM

### Please describe the expected behavior of the issue
Using the Record-then-Verify style via stubbing in property checks with the help of [scalacheck](https://www.scalacheck.org/) should be possible.

### Please provide a description of what actually happens
Using stubs in a property-check test fails with a 'verify should appear after all code under test has been exercised'.

### Reproducible Test Case

Please find the following test-snippet attached. The first test, using stubs and `verify`, fails unfortunately with 'verify should appear after all code under test has been exercised'. The second test, using mock and `expects` works fine.

```scala
import org.scalamock.scalatest.MockFactory
import org.scalatest.{FreeSpec, Matchers}
import org.scalatestplus.scalacheck.ScalaCheckPropertyChecks

class ScalaCheckMockSpec extends FreeSpec with ScalaCheckPropertyChecks with Matchers with MockFactory {
  class Calculator {
    def add(x: Int, y: Int): Int = x + y
  }

  class SystemUnderTest(calculator: Calculator) {
    def add(x: Int, y: Int): Int = calculator.add(x, y)
  }

  "fails" in {
    forAll { (x: Int, y: Int) =>
      val calculatorStub = stub[Calculator]
      val sut = new SystemUnderTest(calculatorStub)

      (calculatorStub.add _)
        .when(*, *)
        .returns(0)

      sut.add(x, y) shouldBe 0

      (calculatorStub.add _).verify(x, y)
    }
  }

  "works fine" in {
    forAll { (x: Int, y: Int) =>
      val calculatorMock = mock[Calculator]
      val sut = new SystemUnderTest(calculatorMock)

      (calculatorMock.add _)
        .expects(x, y)
        .returns(0)

      sut.add(x, y) shouldBe 0
    }
  }
}
```

The only solution I came up with yet is to move the test-execution inside the `forAll` checks what pollutes the test-descriptions:

```scala
  forAll { (x: Int, y: Int) =>
    s"${Random.nextString(1)}: should not fail" in {
      val calculatorStub = stub[Calculator]
      val sut = new SystemUnderTest(calculatorStub)

      (calculatorStub.add _)
        .when(*, *)
        .returns(0)

      sut.add(x, y) shouldBe 0

      (calculatorStub.add _).verify(x, y)
    }
  }
```

Please let me add a Thank You! for maintaining ScalaMock, it is an awesome mocking framework.

**Comment by barkhorn** [comment]
Can you please attach the full stacktrace? There should be one as Verify calls sys.error :)

**Comment by janjaali** [comment]
Sure:

```text
RuntimeException was thrown during property evaluation.
  Message: verify should appear after all code under test has been exercised    
  Occurred when passed generated values (
    arg0 = 0, // 1 shrink
    arg1 = 0 // 31 shrinks
  )
ScalaTestFailureLocation: janjaali.***.blobstorage.ScalaCheckMockSpec at (ScalaCheckMockSpec.scala:19)
org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException: RuntimeException was thrown during property evaluation.
  Message: verify should appear after all code under test has been exercised    
  Occurred when passed generated values (
    arg0 = 0, // 1 shrink
    arg1 = 0 // 31 shrinks
  )
	at org.scalatestplus.scalacheck.UnitCheckerAsserting$$anon$1.indicateFailure(CheckerAsserting.scala:187)
	at org.scalatestplus.scalacheck.UnitCheckerAsserting$$anon$1.indicateFailure(CheckerAsserting.scala:175)
	at org.scalatestplus.scalacheck.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:158)
	at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.forAll(ScalaCheckDrivenPropertyChecks.scala:1041)
	at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.forAll$(ScalaCheckDrivenPropertyChecks.scala:1016)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.forAll(ScalaCheckMockSpec.scala:9)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.$anonfun$new$1(ScalaCheckMockSpec.scala:19)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:405)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.org$scalamock$scalatest$AbstractMockFactory$$super$withFixture(ScalaCheckMockSpec.scala:9)
	at org.scalamock.scalatest.AbstractMockFactory.$anonfun$withFixture$1(AbstractMockFactory.scala:35)
	at org.scalamock.MockFactoryBase.withExpectations(MockFactoryBase.scala:41)
	at org.scalamock.MockFactoryBase.withExpectations$(MockFactoryBase.scala:33)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.withExpectations(ScalaCheckMockSpec.scala:9)
	at org.scalamock.scalatest.AbstractMockFactory.withFixture(AbstractMockFactory.scala:34)
	at org.scalamock.scalatest.AbstractMockFactory.withFixture$(AbstractMockFactory.scala:31)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.withFixture(ScalaCheckMockSpec.scala:9)
	at org.scalatest.FreeSpecLike.invokeWithFixture$1(FreeSpecLike.scala:403)
	at org.scalatest.FreeSpecLike.$anonfun$runTest$1(FreeSpecLike.scala:415)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FreeSpecLike.runTest(FreeSpecLike.scala:415)
	at org.scalatest.FreeSpecLike.runTest$(FreeSpecLike.scala:397)
	at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
	at org.scalatest.FreeSpecLike.$anonfun$runTests$1(FreeSpecLike.scala:474)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:312)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FreeSpecLike.runTests(FreeSpecLike.scala:474)
	at org.scalatest.FreeSpecLike.runTests$(FreeSpecLike.scala:473)
	at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
	at org.scalatest.FreeSpecLike.$anonfun$run$1(FreeSpecLike.scala:518)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FreeSpecLike.run(FreeSpecLike.scala:518)
	at org.scalatest.FreeSpecLike.run$(FreeSpecLike.scala:517)
	at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:312)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
Caused by: java.lang.RuntimeException: verify should appear after all code under test has been exercised
	at scala.sys.package$.error(package.scala:29)
	at org.scalamock.handlers.Verify.handle(CallHandler.scala:125)
	at org.scalamock.handlers.Verify.handle$(CallHandler.scala:125)
	at org.scalamock.function.StubFunction2$$anon$5.handle(StubFunction.scala:58)
	at org.scalamock.function.StubFunction2$$anon$5.handle(StubFunction.scala:58)
	at org.scalamock.handlers.UnorderedHandlers.$anonfun$handle$1(UnorderedHandlers.scala:30)
	at org.scalamock.handlers.UnorderedHandlers.$anonfun$handle$1$adapted(UnorderedHandlers.scala:29)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
	at org.scalamock.handlers.UnorderedHandlers.handle(UnorderedHandlers.scala:29)
	at org.scalamock.function.FakeFunction.handle(FakeFunction.scala:44)
	at org.scalamock.function.FakeFunction2.apply(FakeFunction.scala:69)
	at janjaali.***.blobstorage.ScalaCheckMockSpec$$anon$1.add(ScalaCheckMockSpec.scala:20)
	at janjaali.***.blobstorage.ScalaCheckMockSpec$SystemUnderTest.add(ScalaCheckMockSpec.scala:15)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.$anonfun$new$2(ScalaCheckMockSpec.scala:27)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.$anonfun$new$2$adapted(ScalaCheckMockSpec.scala:19)
	at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.liftedTree11$1(ScalaCheckDrivenPropertyChecks.scala:1028)
	at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.$anonfun$forAll$13(ScalaCheckDrivenPropertyChecks.scala:1027)
	at org.scalacheck.Prop$.$anonfun$forAll$18(Prop.scala:921)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:761)
	at org.scalacheck.Prop$.secure(Prop.scala:471)
	at org.scalacheck.Prop$.result$1(Prop.scala:761)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$4(Prop.scala:770)
	at scala.collection.immutable.Stream.map(Stream.scala:168)
	at org.scalacheck.Prop$.getFirstFailure$1(Prop.scala:770)
	at org.scalacheck.Prop$.shrinker$1(Prop.scala:780)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:802)
	at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:307)
	at org.scalacheck.PropFromFun.apply(Prop.scala:22)
	at org.scalacheck.Prop$.result$1(Prop.scala:762)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$4(Prop.scala:770)
	at scala.collection.immutable.Stream.map(Stream.scala:168)
	at org.scalacheck.Prop$.getFirstFailure$1(Prop.scala:770)
	at org.scalacheck.Prop$.shrinker$1(Prop.scala:780)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:802)
	at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:307)
	at org.scalacheck.PropFromFun.apply(Prop.scala:22)
	at org.scalacheck.Test$.workerFun$1(Test.scala:326)
	at org.scalacheck.Test$.$anonfun$check$1(Test.scala:355)
	at org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:355)
	at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
	at org.scalacheck.Test$.check(Test.scala:355)
	at org.scalatestplus.scalacheck.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:88)
	... 57 more
```

**Comment by barkhorn** [comment]
Something else you can try is to wrap your code like this:
```
forAll { (x: Int, y: Int) => withExpectations {
      val calculatorStub = stub[Calculator]
      val sut = new SystemUnderTest(calculatorStub)

      (calculatorStub.add _)
        .when(*, *)
        .returns(0)

      sut.add(x, y) shouldBe 0

      (calculatorStub.add _).verify(x, y)
    }}
```

**Comment by janjaali** [comment]
Tried it out, unfortunately a NullPointerException is thrown now:

```text
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at org.scalamock.MockFactoryBase.verifyExpectations(MockFactoryBase.scala:86)
	at org.scalamock.MockFactoryBase.withExpectations(MockFactoryBase.scala:42)
	at org.scalamock.MockFactoryBase.withExpectations$(MockFactoryBase.scala:33)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.withExpectations(ScalaCheckMockSpec.scala:7)
	at org.scalamock.scalatest.AbstractMockFactory.withFixture(AbstractMockFactory.scala:34)
	at org.scalamock.scalatest.AbstractMockFactory.withFixture$(AbstractMockFactory.scala:31)
	at janjaali.***.blobstorage.ScalaCheckMockSpec.withFixture(ScalaCheckMockSpec.scala:7)
	at org.scalatest.FreeSpecLike.invokeWithFixture$1(FreeSpecLike.scala:403)
	at org.scalatest.FreeSpecLike.$anonfun$runTest$1(FreeSpecLike.scala:415)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FreeSpecLike.runTest(FreeSpecLike.scala:415)
	at org.scalatest.FreeSpecLike.runTest$(FreeSpecLike.scala:397)
	at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
	at org.scalatest.FreeSpecLike.$anonfun$runTests$1(FreeSpecLike.scala:474)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:312)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FreeSpecLike.runTests(FreeSpecLike.scala:474)
	at org.scalatest.FreeSpecLike.runTests$(FreeSpecLike.scala:473)
	at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
	at org.scalatest.FreeSpecLike.$anonfun$run$1(FreeSpecLike.scala:518)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FreeSpecLike.run(FreeSpecLike.scala:518)
	at org.scalatest.FreeSpecLike.run$(FreeSpecLike.scala:517)
	at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:312)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```

Thanks for your quick-reply :)

**Comment by barkhorn** [comment]
Hm ok, this must be some weird interaction with ScalaCheck then. was worth a try :/

**Comment by janjaali** [comment]
PS: I also tried it with `OneInstancePerTest` and with fixture contexts as suggested in <https://scalamock.org/user-guide/sharing-scalatest/>.

**Comment by barkhorn** [comment]
Fixed. The test fixture clashes with the delegated verification of ScalaCheck (which effectively runs multiple sub-tests for the forEach).
Switch autoVerify off and explicitely state where the context should start/end with withExpectations:

```
import org.scalamock.scalatest.MockFactory
import org.scalatest.{FreeSpec, Matchers}
import org.scalatestplus.scalacheck.ScalaCheckPropertyChecks

class Issue272Test extends FreeSpec with ScalaCheckPropertyChecks with Matchers with MockFactory {
  autoVerify = false

  class Calculator {
    def add(x: Int, y: Int): Int = x + y
  }

  class SystemUnderTest(calculator: Calculator) {
    def add(x: Int, y: Int): Int = calculator.add(x, y)
  }

  "fails" in {
    forAll { (x: Int, y: Int) => withExpectations {
      val calculatorStub = stub[Calculator]
      val sut = new SystemUnderTest(calculatorStub)

      (calculatorStub.add _).when(*, *).returns(0)

      sut.add(x, y) shouldBe 0
      (calculatorStub.add _).verify(x, y)
    }}
  }

  "works fine" in {
    forAll { (x: Int, y: Int) => withExpectations {
      val calculatorMock = mock[Calculator]
      val sut = new SystemUnderTest(calculatorMock)

      (calculatorMock.add _)
        .expects(x, y)
        .returns(0)

      sut.add(x, y) shouldBe 0
    }}
  }
}
```

**Comment by janjaali** [comment]
Works like a charm, thanks for your help and investigation.
