### ISSUE TITLE
java.lang.NoSuchMethodError while initializing ScalaTest class with MockFactory mixed in

### ISSUE THREAD

**Issue by hindog** [paulbutcher/ScalaMock#369]
### ScalaMock Version (e.g. 3.5.0)
4.4.0 (also tried 5.1.0) 

### ScalaTest Version
3.1.0

(Quickstart shows ScalaMock 4.4.0 and ScalaTest 3.1.0: https://scalamock.org/quick-start/)

### Scala Version (e.g. 2.12)
2.12.12

### Runtime (JVM or JS)
JVM 11.0

### Please describe the expected behavior of the issue

Trying to run a unit test with `MockFactory` mixed in but getting `java.lang.NoSuchMethodError` on test class initialization

### Please provide a description of what actually happens

`java.lang.NoSuchMethodError` is thrown during test class initialization:

```
An exception or error caused a run to abort: 'void org.scalamock.clazz.Mock.$init$(org.scalamock.clazz.Mock)' 
java.lang.NoSuchMethodError: 'void org.scalamock.clazz.Mock.$init$(org.scalamock.clazz.Mock)'
	at foo.TestFoo.<init>(TestFoo.scala:5)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1396)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$8(Runner.scala:1199)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1198)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1474)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:40)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```

### Reproducible Test Case

```scala
package foo

class TestFoo extends org.scalatest.flatspec.AnyFlatSpecLike with org.scalamock.scalatest.MockFactory {
  "Foo" should "run ok" in {
    assert(true)
  }
}
```

**Comment by hindog** [comment]
Nevermind, found the issue.  I had accidently pulled in the Scala 2.11 (needed 2.12) with:

```
libraryDependencies += "org.scalamock" % "scalamock_2.11" % "4.4.0" % Test
```
