### ISSUE TITLE
UninitializedFieldError when trying to mock class that implements a self-type with field depending on method implemented in conrete class

### ISSUE THREAD

**Issue by tmirzoev** [paulbutcher/ScalaMock#373]
### ScalaMock Version: 
4.4.0
### Scala Version: 
2.13.3
### Runtime 
Adopt OpenJDK 11.0.10

### Please describe the expected behavior of the issue
I've got a trait and a class. The trait contains a field that is initialized with a method call, and this method is not defined but relies on implementation in extending class.
Then, I have a class that extends this trait and provides implementation for the method in trait.
ScalaMock should be able to mock the class

### Please provide a description of what actually happens
The real class works in code, the test that uses the mock compiles, but when it runs I receive an UninitializedFieldError:
`
An exception or error caused a run to abort: Uninitialized field: /somePath/SomeTestSpec.scala: 23 
scala.UninitializedFieldError: Uninitialized field: /somePath/SomeTestSpec.scala: 23
	at somePackage.SomeTestSpec$$anon$1.mock$b$0(SomeTestSpec.scala:23)
	at somePackage.SomeTestSpec$$anon$1.b(SomeTestSpec.scala:23)
	at somePackage.SomeTestSpec$B.$init$(SomeTestSpec.scala:20)
	at somePackage.SomeTestSpec$Impl.<init>(SomeTestSpec.scala:10)
	at somePackage.SomeTestSpec$$anon$1.<init>(SomeTestSpec.scala:23)
	at somePackage.SomeTestSpec.<init>(SomeTestSpec.scala:23)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1431)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$8(Runner.scala:1239)
	at scala.collection.immutable.List.map(List.scala:246)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1238)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
`

### Reproducible Test Case

```
import org.scalamock.scalatest.MockFactory
import org.scalatest.FlatSpecLike

class SomeTestSpec extends FlatSpecLike with MockFactory {


  class Impl extends  B {
    override protected def b(): Int = 2
  }

  trait B {
    protected def b(): Int

    protected final val test = b()
  }

  val m = stub[Impl]
}
```

**Comment by barkhorn** [comment]
your `Impl` overrides `b` and the initialisation of `B` runs before that mocked method has an implementation.
That is why you should never call non-final methods in a constructor.
It's not a bug but just how the JVM works.

**Comment by tmirzoev** [comment]
Well, yes, coming to think of it. Thank you for the clarification. 

The problem is, it's not "mine", it is how Akka supposes me to use its event bus with a certain classifier, as you can see here https://github.com/akka/akka/blob/7b3667a07096092d353b8eb7bdbf90831bbc208f/akka-actor/src/main/scala/akka/event/EventBus.scala#L83

I am in no way defending them, or implying that this problem is on scalamock's side. But is there any way to circumvent this and mock such a class with scalamock?
