### ISSUE TITLE
Scala 3 regression from Scala 2.13 expected a term symbol but received val <none>

### ISSUE THREAD

**Issue by KarelCemus** [paulbutcher/ScalaMock#503]
### ScalaMock Version (e.g. 3.5.0)

6.0.0-M1

### Scala Version (e.g. 2.12)

3.3.0

### Runtime (JVM or JS)

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-120.04)

### Please describe the expected behavior of the issue

This code should compile, it compiles with Scala 2.13. Strange thing is that there are used 2 features  (a default value and a type parameter), when used separately it works, when used together it fails.

### Please provide a description of what actually happens

The compiler fails with 

```
[error] 252 |      val foo = mock[Foo]
[error]     |                      ^^^^^^^^^
[error]     |Exception occurred while executing macro expansion.
[error]     |java.lang.AssertionError: assertion failed: expected a term symbol but received val <none>
[error]     |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:279)
[error]     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$DefDef$.apply(QuotesImpl.scala:278)
[error]     |	at org.scalamock.clazz.MockMaker$.$anonfun$8(MockMaker.scala:183)
[error]     |	at scala.collection.immutable.List.flatMap(List.scala:293)
[error]     |	at org.scalamock.clazz.MockMaker$.instance(MockMaker.scala:186)
[error]     |	at org.scalamock.clazz.MockImpl$.mock(MockImpl.scala:35)
[error]     |
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Mock.scala:32
[error]      ---------------------------------------------------------------------------

```

### Reproducible Test Case

Please provide a minimised code snippet that fails, ideally, written as a failing test case in ScalaTest.
This will help us a lot in diagnosing the problem and work on a fix.
If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

```scala
 
trait Foo1 {
  def foo[T](unit: Int): Unit
}

trait Foo2 {
  def foo(unit: Int = 5): Unit
}

trait Foo3{
  def foo[T](unit: Int = 5): Unit
}

test("should compile and works 1") {
  assertCompiles {
    "val foo = mock[Foo1]"
  }
}

test("should compile and works 2") {
  assertCompiles {
    "val foo = mock[Foo2]"
  }
}

test("should compile but fails") {
  assertCompiles {
    "val foo = mock[Foo3]"
  }
}
```

**Comment by goshacodes** [comment]
On it

**Comment by goshacodes** [comment]
Fix in 6.0.0-M2
