### ISSUE TITLE
StackOverflow for toString on mock

### ISSUE THREAD

**Issue by fgeller** [paulbutcher/ScalaMock#58]
I get a StackOverflowError for the following snippet

scala version: 2.10.3
scalamock:  "org.scalamock" %% "scalamock-scalatest-support" % "3.1.RC1"
scalatest: "org.scalatest" %% "scalatest" % "2.1.0"

let me know if i can be of any further help :)

``` scala
import org.scalatest.FunSpec
import org.scalatest.Matchers
import org.scalamock.scalatest.MockFactory

class HelloWorldTest extends FunSpec with Matchers with MockFactory {

  trait Pen {
    def name = "hans"
    override def toString = name
  }

  trait Author { def something(p: Pen) = "blaaa" }

    it("test it!") {
      val mockPen = mock[Pen]
      val mockAuthor = mock[Author]

      // (mockAuthor.something(_: Pen)).expects(*).returning("blubb")
      (mockAuthor.something(_: Pen)).expects(new Pen { /* supposed to fail */ }).returning("blubb")

      mockAuthor.something(mockPen)
    }
}
```

this is the Error shortened to one screen:

```
> last test:test
[info] HelloWorldTest:
[error] Uncaught exception when running HelloWorldTest: java.lang.StackOverflowError
java.lang.StackOverflowError
        at java.lang.StringBuilder.<init>(StringBuilder.java:97)
        at scala.collection.mutable.StringBuilder.<init>(StringBuilder.scala:46)
        at scala.collection.mutable.StringBuilder.<init>(StringBuilder.scala:51)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1157)
        at org.scalamock.ArgumentMatcher.toString(ArgumentMatcher.scala:27)
        at java.lang.String.valueOf(String.java:2854)
        at java.lang.StringBuilder.append(StringBuilder.java:128)
        at scala.StringContext.standardInterpolator(StringContext.scala:122)
        at scala.StringContext.s(StringContext.scala:90)
        at org.scalamock.CallHandler.toString(CallHandler.scala:81)
        at org.scalamock.Handlers$$anonfun$toString$1.apply(Handlers.scala:35)
        at org.scalamock.Handlers$$anonfun$toString$1.apply(Handlers.scala:34)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.scalamock.Handlers.toString(Handlers.scala:34)
        at java.lang.String.valueOf(String.java:2854)
        at java.lang.StringBuilder.append(StringBuilder.java:128)
        at scala.StringContext.standardInterpolator(StringContext.scala:122)
        at scala.StringContext.s(StringContext.scala:90)
        at org.scalamock.MockFactoryBase$class.errorContext(MockFactoryBase.scala:148)
        at org.scalamock.MockFactoryBase$class.reportUnexpectedCall(MockFactoryBase.scala:123)
        at HelloWorldTest.reportUnexpectedCall(Test.scala:5)
        at org.scalamock.MockFunction$class.onUnexpected(MockFunction.scala:25)
        at org.scalamock.MockFunction0.onUnexpected(MockFunction.scala:28)
        at org.scalamock.MockFunction0.onUnexpected(MockFunction.scala:28)
        at org.scalamock.FakeFunction$$anonfun$handle$1.apply(FakeFunction.scala:38)
        at scala.Option.getOrElse(Option.scala:120)
        at org.scalamock.FakeFunction.handle(FakeFunction.scala:38)
        at org.scalamock.FakeFunction0.apply(FakeFunction.scala:47)
        at HelloWorldTest$$anonfun$1$$anon$1.name(Test.scala:15)
        at HelloWorldTest$Pen$class.toString(Test.scala:9)
...
```

**Comment by lhohan** [comment]
:+1:

**Comment by blueguitarenator** [comment]
I'm still getting this error almost two years later!!

scalaVersion  := "2.11.8"
"org.scalamock" %% "scalamock-scalatest-support" % "3.2.2" % "test"

**Comment by barkhorn** [comment]
at the moment, you cannot test methods which are defined on java.lang.Object (toString, hashCode, ...)

if you add this before your test action, you will not get the problem.
```
    mockPen.name _ expects() returning "zzz" anyNumberOfTimes()
```

The stackoverflow originates from the library trying to print the list of unexpected calls, but as toString refers to a mocked method, it gets stuck in a loop.
Bit of a usability error, but not exactly a bug either.

output after:
```
Unexpected call: <mock-2> Author.something(zzz)

Expected:
inAnyOrder {
  <mock-1> Pen.name() any number of times (called once)
  <mock-2> Author.something(hans) once (never called - UNSATISFIED)
}

Actual:
  <mock-2> Author.something(zzz)
  <mock-1> Pen.name()
  <mock-1> Pen.name()
ScalaTestFailureLocation: scala.Option at (Option.scala:120)
org.scalatest.exceptions.TestFailedException: Unexpected call: <mock-2> Author.something(zzz)

Expected:
inAnyOrder {
  <mock-1> Pen.name() any number of times (called once)
  <mock-2> Author.something(hans) once (never called - UNSATISFIED)
}

Actual:
  <mock-2> Author.something(zzz)
  <mock-1> Pen.name()
  <mock-1> Pen.name()
	at org.scalamock.scalatest.AbstractMockFactory$class.newExpectationException(AbstractMockFactory.scala:51)
	...
```
