### ISSUE TITLE
Mocking classes with non-trivial constructor results in NPE

### ISSUE THREAD

**Issue by gavares** [paulbutcher/ScalaMock#96]
First, thanks for writing ScalaMock. Great library seems to fit much better than Mockito in the scala toolset.

The issue I'm having: anytime I try to mock or stub MulticastSocket (from the jdk) I get an NPE thrown from within the `MulticastSocket` constructor when, during initialization, it tries to execute `setReuseAddress`  (see stacktrace below) . Simple test example:

``` scala
import java.net.MulticastSocket

import org.scalamock.scalatest.MockFactory
import org.scalatest.FlatSpec

class StubSpec extends FlatSpec with MockFactory {

  class FakeSocket extends MulticastSocket

  "ScalaMock" should "mock a MulticastSocket" in {
    val socket = stub[FakeSocket]
  }

}
```

This results in:

```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
    at playi.service.StubSpec$$anonfun$1$$anon$1.setReuseAddress(StubSpec.scala:17)
    at java.net.MulticastSocket.<init>(MulticastSocket.java:168)
    at java.net.MulticastSocket.<init>(MulticastSocket.java:111)
    at playi.service.StubSpec$FakeSocket.<init>(StubSpec.scala:14)
    at playi.service.StubSpec$$anonfun$1$$anon$1.<init>(StubSpec.scala:17)
    at playi.service.StubSpec$$anonfun$1.apply$mcV$sp(StubSpec.scala:17)
    at playi.service.StubSpec$$anonfun$1.apply(StubSpec.scala:16)
    at playi.service.StubSpec$$anonfun$1.apply(StubSpec.scala:16)
    at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    at org.scalatest.Transformer.apply(Transformer.scala:22)
    at org.scalatest.Transformer.apply(Transformer.scala:20)
    at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
    at org.scalamock.scalatest.AbstractMockFactory$$anonfun$withFixture$1.apply(AbstractMockFactory.scala:35)
    at org.scalamock.scalatest.AbstractMockFactory$$anonfun$withFixture$1.apply(AbstractMockFactory.scala:34)
    at org.scalamock.MockFactoryBase$class.withExpectations(MockFactoryBase.scala:41)
    at playi.service.StubSpec.withExpectations(StubSpec.scala:12)
    at org.scalamock.scalatest.AbstractMockFactory$class.withFixture(AbstractMockFactory.scala:34)
    at playi.service.StubSpec.withFixture(StubSpec.scala:12)
    at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
    at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
    at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
    at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
    at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1683)
    at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
    at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
    at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714)
    at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1683)
    at org.scalatest.Suite$class.run(Suite.scala:1424)
    at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1683)
    at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
    at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
    at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760)
    at org.scalatest.FlatSpec.run(FlatSpec.scala:1683)
    at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
    at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
    at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
    at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
    at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
    at org.scalatest.tools.Runner$.run(Runner.scala:883)
    at org.scalatest.tools.Runner.run(Runner.scala)
```

I can change `stub[MulticastSocket]` to `mock[MulticastSocket]` and I still get the same result.

Thanks

**Comment by pawel-wiejacha** [comment]
The smaller example that exposes this bug is:

```scala
    class Foo {
        getValue() + 1 // calling method in the constructor
        def getValue() = 5
    }
    val m = mock[Foo]
```
When a base class constructor is called, mocked methods are not initialized. So when a base class constructor calls a non-final method, the forwarder forwards the call to the null `MockFunction` field and the NPE is thrown.

**Comment by ppiotrow** [comment]
Is there possibility to ignore all calls in constructor (only set expectations and returns on mock)? I have non-trivial one, that tries to connect to remote service (what I'd like to avoid in my unit tests).

**Comment by pawel-wiejacha** [comment]
@ppiotrow Unfortunately, you can't.

**Comment by mauhiz** [comment]
Is there any known workaround for this issue?

**Comment by bkowalik** [comment]
@ppiotrow I think that this is bad practice to make such calls in constructor. Especially look at this snippet
```scala
class Foo {
	foo()
	def foo() = println(1)
}

class Bar extends Foo {
	val a: Any = 2
	override def foo() = println(a)
}
```
The `Bar::a` is explicite `scala.Any` to point that using polymorphism in constructor calls is wrong and could cause confusion. Maybe better would be to make this call after constructing object.

**Comment by ppiotrow** [comment]
@bkowalik I agree, but as I remember this case (which was ~10 months) ago I was using external library with such bad patterns.

**Comment by bkowalik** [comment]
@ppiotrow Is it Java library or Scala? You can also construct simple Proxy so that every call to this class object will go through. You will be able to mock and for example if it is Java library pack every call to `Try` or something like that.

**Comment by ppiotrow** [comment]
@bkowalik It was Java client to some service. Yep, proxy is good solution.

**Comment by logarithm** [comment]
Hey guys! I'm trying to use ScalaMock for `AmazonEC2Client` and faced with exactly the same issue. Of course I can create workaround for this issue but it would be better to use ScalaMock straightforward without workarounds.

**Comment by barkhorn** [comment]
@logarithm got a stacktrace? also, what version of ScalaMock did you use?
Not reopening this for now as I suspect this caused by the same problem - a constructor calling a method that has been stubbed out. Not much we can do about it - maybe with scala.meta in the future.

**Comment by logarithm** [comment]
I use "org.scalamock" %% "scalamock-scalatest-support" % "3.5.0" in my project. Since my project is not open-sourced yet I replaced full path in stack trace by just `MyTestClass`

```
*** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at MyTestClass$$anonfun$1$$anon$1.setEndpoint(MyTestClass.scala:41)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.init(AmazonEC2Client.java:229)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.<init>(AmazonEC2Client.java:220)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.<init>(AmazonEC2Client.java:194)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.<init>(AmazonEC2Client.java:90)
[info]   at MyTestClass$$anonfun$1$$anon$1.<init>(MyTestClass.scala:41)
[info]   at MyTestClass$$anonfun$1.apply$mcV$sp(MyTestClass.scala:41)
[info]   at MyTestClass$$anonfun$1.apply(MyTestClass.scala:29)
[info]   at MyTestClass$$anonfun$1.apply(MyTestClass.scala:29)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   ...
```

AWS Java SDK version is 1.10.58

**Comment by barkhorn** [comment]
yes, unfortunately that constructor calls `private void init()`, which would not be defined at the time of mocking yet. Not fixable with Scala macros, but we should be able to address it by using scala.meta
Instead of mocking the whole class, can you make use of the abstract class/interface `AmazonWebServiceClient` or `AmazonEC2`?

**Comment by logarithm** [comment]
I can reproduce this NPE on small test class:
```
class TestMock
{
  this.testMethod()
  def testMethod(): Unit = {}
}
```
If you try to mock this class you will get NPE. Maybe it might help to eliminate this bug.

`AmazonEC2` should work, thanks!

**Comment by barkhorn** [comment]
Thanks again, but the answer is still the same unfortunately.
A constructor that calls a virtual/overridable method just isn't mockable at the moment. This is not a bug but a limitation of macros in Scala.

**Comment by logarithm** [comment]
Sure thing! Thanks for quick reply! I hope even this non trivial case will be working soon!

**Comment by dclifton-hmrc** [comment]
We ran into the same problem today when attempting to port one of our mockito tests to scalamock.  The library we were using has a non-trivial constructor and mocking it fails with an NPE.

We have a desire to move away from mockito but issues like this hamper such progress.

Is a solution for this planned for a later scalamock version?

**Comment by barkhorn** [comment]
Hi @dclifton-hmrc . Unfortunately ScalaMock can't fix this issue, as all macro mocks are actual subclasses of the type-to-mock, so their constructor will *always* run. You could try using a proxy mock (e.g. via MixedMockFactory) and see if that helps. Proxy mocks only work on the JVM as a backend (not on scala-js)
